<a href="https://colab.research.google.com/github/JanManuell/MiPrimerPrograma/blob/main/numpyBases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array(56.7)

In [ ]:
b = np.array([5,6,7,-3])

In [ ]:
c = np.array([[2,3],[-1,7]])

In [ ]:
print(c)

[[ 2  3]
 [-1  7]]


Elemento x elemento

In [ ]:
operacion = c+a
print(operacion)

[[58.7 59.7]
 [55.7 63.7]]


Operaciones no exe

In [ ]:
#Producto punto
v1 = np.array([4,5,7,9])
v2 = np.array([-1,4,6,7])
operacion = np.dot(v1,v2)
print(operacion)

121


In [ ]:
#Producto matricial
m1 = np.array([[2,1],[0,-1]])
m2 = np.array([[3,2],[1,-2]])
operacion = np.matmul(m1,m2)
print(operacion)

[[ 7  2]
 [-1  2]]


### **Conversion entre dimensiones**

In [ ]:
print(a.shape) #Elemento escalar sin dimensión

()


In [ ]:
a = a.reshape(1) #Conversion a un vector
print(a)         #Visualisamos el nuevo vector generado
print (a.shape)  #Visualisamos la dimensión

[56.7]
(1,)


In [ ]:
print(b)

[ 5  6  7 -3]


In [ ]:
b = b.reshape(1,4)  #Re-escalamos a una matriz
print(b)
print(b.shape)

[[ 5  6  7 -3]]
(1, 4)


In [ ]:
print(c)         #Valor de c

[[ 2  3]
 [-1  7]]


In [ ]:
c = c.reshape(4) #Re-escalamos a un vector de tamaño 4
print(c)
print(c.shape)

[ 2  3 -1  7]
(4,)
